name: publish-dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version (e.g. 1.0.0)'
        required: true

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (stable)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VERSION=3.24
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ inputs.version }}
          push: true

      - name: Build and push (edge)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VERSION=edge
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}:edge
            ghcr.io/${{ github.repository }}:edge-${{ inputs.version }}
          push: true
